Output welcome.gif

Set Theme "Catppuccin Mocha"
Set Padding 20
Set FontFamily "JetBrainsMono Nerd Font"

Set Shell "bash"
Set FontSize 32
Set Width 750
Set Height 100

Type "Welcome to my profile! ✨ "
Sleep 2s
Backspace 24
Sleep 0.4s
Type "Check out dwm-mko!"
Sleep 3s
Left 1
Backspace 7
Type "dotfiles-installer"
Right 1
Sleep 3s
Left 1
Backspace 18
Type "nvim-mko"
Right 1
Sleep 3s
Backspace 19
Type "Have a good day! ☀️ "


Sleep 5s
